# Generated by Django 3.2.8 on 2021-10-30 07:32

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile',
            field=sorl.thumbnail.fields.ImageField(default=0, upload_to='profiles'),
            preserve_default=False,
        ),
    ]
