# Generated by Django 3.2.8 on 2021-10-31 08:07

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0004_auto_20211031_0731'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=sorl.thumbnail.fields.ImageField(default=0, upload_to='Post'),
            preserve_default=False,
        ),
    ]
