# Generated by Django 3.2.9 on 2021-11-02 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0008_alter_post_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
    ]
