# Generated by Django 3.2.9 on 2021-11-09 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
        ('feed', '0017_alter_comment_text'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='like',
            unique_together={('by', 'post')},
        ),
    ]
