# Generated by Django 3.2.9 on 2021-11-03 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
        ('direct_messages', '0002_message_time'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='message',
            unique_together={('sender', 'reciever')},
        ),
    ]
