# Generated by Django 3.2.9 on 2021-11-03 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=80)),
                ('notified_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notified_to', to='profiles.profile')),
                ('notifier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifier', to='profiles.profile')),
            ],
        ),
    ]
